api:
    security:
        token:
            secret: ${JWT_SECRET:987654321}
            expires: 2400
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/ekan
        username: root
        password: root
    jpa:
        show-sql: true
        properties:
            hibernate:
                format_sql: true
server:
    error:
        include-stacktrace: never